platform :ios, '8.0'

target 'YOHappyChat' do

    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Happy Chat
    pod 'BmobSDK'
    pod 'SVProgressHUD'
    pod 'ChameleonFramework'
    pod 'Alamofire'



end
